version: "3.8"
services:
  db:
    image: postgres:17
    container_name: db_app
    command: -p 5432
    expose:
      - 5432
    env_file:
      - .env
  app:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: stockroom_api
    command: sh /app/docker/app.sh
    ports:
      - 8000:8000
    depends_on:
      - db